ALTER TABLE todo
    ADD COLUMN IF NOT EXISTS is_completed BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS is_incomplete BOOLEAN DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS is_pending BOOLEAN DEFAULT FALSE;